# For Presets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-collector
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

- apiGroups: ["apps/v1"] 
  resources: ["replicasets","daemonsets"] 
  verbs: ["watch","list","get"] 

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-collector
subjects:
- kind: ServiceAccount
  name: opentelemetry-collector
  namespace: default
roleRef:
  kind: ClusterRole
  name: opentelemetry-collector
  apiGroup: rbac.authorization.k8s.io
