sloth:
  resyncInterval: "15m"    # The controller resync interval duration (e.g 15m).
  workers: 5            # The number of concurrent controller workers (e.g 5).
  labelSelector: ""     # Sloth will handle only the ones that match the selector.
  namespace: ""         # The namespace where sloth will the CRs to process.
  extraLabels: {}       # Labels that will be added to all the generated SLO Rules.
  defaultSloPeriod: ""  # The slo period used by sloth (e.g. 30d).
  optimizedRules: true  # Reduce prom load for calculating period window burnrates.
  debug:
    enabled: true
  # Could be: default or json
  logger: json
