apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: grafana/tns-app:latest
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        - http://db
        ports:
        - name: http-metrics
          containerPort: 80
        env:
        - name: JAEGER_AGENT_HOST
          value: opentelemetry-collector.default.svc.cluster.local
        - name: JAEGER_TAGS
          value: cluster=docker,namespace=default # demo?
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: app
spec:
  type: NodePort
  selector:
    name: app
  ports:
  - protocol: TCP
    nodePort: 30030
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - name: db
        image: grafana/tns-db:latest
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        ports:
        - name: http-metrics
          containerPort: 80
        env:
        - name: JAEGER_AGENT_HOST
          value: opentelemetry-collector.default.svc.cluster.local
        - name: JAEGER_TAGS
          value: cluster=docker,namespace=default # demo ?
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: db
spec:
  selector:
    name: db
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      name: loadgen
  template:
    metadata:
      labels:
        name: loadgen
    spec:
      containers:
      - name: loadgen
        image: grafana/tns-loadgen:latest
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        - http://app
        ports:
        - name: http-metrics
          containerPort: 80
        env:
        - name: JAEGER_AGENT_HOST
          value: opentelemetry-collector.default.svc.cluster.local
        - name: JAEGER_TAGS
          value: cluster=docker,namespace=default # demo?
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: loadgen
spec:
  selector:
    name: loadgen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
