---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app
  namespace: prometheus
spec:
  endpoints:
  - honorLabels: true
    port: http-metrics
    path: /metrics
    scheme: http
    scrapeTimeout: 30s
  jobLabel: app
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      name: app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: db
  namespace: prometheus
spec:
  jobLabel: db
  selector:
    matchLabels:
      name: db
  endpoints:
  - port: http-metrics
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loadgen
  namespace: prometheus
spec:
  jobLabel: loadgen
  selector:
    matchLabels:
      name: loadgen
  endpoints:
  - port: http-metrics
    path: /metrics
    # relabelings:
    # - action: replace
    #   replacement: default/$1
    #   sourceLabels:
    #   - job
    #   targetLabel: job
    # - action: replace
    #   replacement: loki
    #   targetLabel: cluster
