---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app
spec:
  # jobLabel: app
  endpoints:
  - port: http-metrics
    path: /metrics
    scheme: http
  selector:
    matchLabels:
      name: app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: db
spec:
  # jobLabel: db
  endpoints:
  - port: http-metrics
    path: /metrics
  selector:
    matchLabels:
      name: db
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loadgen
spec:
  # jobLabel: loadgen
  endpoints:
  - port: http-metrics
    path: /metrics
  selector:
    matchLabels:
      name: loadgen
    # relabelings:
    # - action: replace
    #   replacement: default/$1
    #   sourceLabels:
    #   - job
    #   targetLabel: job
    # - action: replace
    #   replacement: loki
    #   targetLabel: cluster
    # - sourceLabels: [__meta_kubernetes_pod_container_port_name]
    #   action: keep
    #   regex: '.*-envoy-prom'
    # - action: labeldrop
    #   regex: "__meta_kubernetes_pod_label_(.+)"
    # - sourceLabels: [__meta_kubernetes_namespace]
    #   action: replace
    #   targetLabel: namespace
    # - sourceLabels: [__meta_kubernetes_pod_name]
    #   action: replace
    #   targetLabel: pod_name
