---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: demo
  labels:
    name: app
spec:
  type: ClusterIP
  selector:
    name: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: demo
  labels:
    name: db
spec:
  type: ClusterIP
  selector:
    name: db
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadgen
  namespace: demo
  labels:
    name: loadgen
spec:
  type: ClusterIP
  selector:
    name: loadgen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
