---
kind: Service
apiVersion: v1
metadata:
  name: app
  namespace: demo
  labels:
    name: app
spec:
  type: NodePort
  selector:
    name: app
  ports:
  - protocol: TCP
    nodePort: 30030
    port: 80
    targetPort: 80
    name: http-metrics
---
kind: Service
apiVersion: v1
metadata:
  name: db
  namespace: demo
  labels:
    name: db
spec:
  type: ClusterIP
  selector:
    name: db
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http-metrics
---
kind: Service
apiVersion: v1
metadata:
  name: loadgen
  namespace: demo
  labels:
    name: loadgen
spec:
  type: ClusterIP
  selector:
    name: loadgen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http-metrics
